fixtures:
  symlinks:
    contrail: "#{source_dir}"
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "2.6.0"
    sysctl:
      repo: https://github.com/duritong/puppet-sysctl
      ref: 3b027e816818f2c1086075038ac9b4af1cadbc24
    apt:
      repo: https://github.com/puppetlabs/puppetlabs-apt
      ref: 1.6.0
    inifile:
      repo: https://github.com/puppetlabs/puppetlabs-inifile.git
      ref: 41e2ddbc1cd861247e57d16b778cbe891602f509
    network:
      repo: https://github.com/adrienthebo/puppet-network
      ref: 0.4.1
    filemapper:
      repo: https://github.com/adrienthebo/puppet-filemapper
      ref: 1.1.3
